In [14]:
#values: 0,1,2,3...
import numpy as np
data = np.loadtxt('input.txt', dtype = np.int32)
print(data)
dim = data.shape[0]

[[0 0 0]
 [0 1 2]
 [0 2 1]]


In [15]:
#check for commutativity
def check_for_com(data):
    is_com = True
    for (i, j), x in np.ndenumerate(data):
        is_com = is_com and x == data[j,i]
    return is_com    

In [16]:
#check for neutral

def check_array(arr):
    for i, x in np.ndenumerate(arr):
        if i != x:
            return False
    else:
        return True

def get_neutral(is_com, data):
    neutr_mask_rows = np.apply_along_axis(check_array, axis=1, arr=data)
    neutral_rows = next((i for i, x in enumerate(neutr_mask_rows) if x), None)
    if not is_com:
        neutral = neutral_rows if check_array(data[:, neutral_rows]) else None
    else:
        neutral = neutral_rows
    return neutral
    

In [17]:
#check for reversibility

def check_for_rev(is_com, neutral, data): 
    
    def check_array_for_neutral(arr, neutral = neutral):
        for x in np.nditer(arr):
            if x == neutral:
                return True
        else:
            return False
    
    if neutral is None:
        is_rev = False
    else:
        neutr_is_in_row = np.apply_along_axis(check_array_for_neutral, axis=1, arr=data)
        no_neutral_row = next((i for i, x in enumerate(neutr_is_in_row) if not x), None)

        if no_neutral_row is None:
            if not is_com:
                neutr_is_in_col = np.apply_along_axis(check_array_for_neutral, axis=1, arr=data.T)
                no_neutral_col = next((i for i, x in enumerate(neutr_is_in_row) if not x), None)
                is_rev = no_neutral_col is None
            else:
                is_rev = True    
        else:
            is_rev = False
    return is_rev        
    

In [18]:
#check for associativity

def check_for_assoc(data):
    is_assoc = True
    for (i,j), x in np.ndenumerate(data):
        for k in range(dim):
            is_assoc = is_assoc and data[x,k] == data[i,data[j,k]]
    return is_assoc
    

In [19]:
is_assoc = check_for_assoc(data)

if is_assoc:
    is_com = check_for_com(data)
    neutral = get_neutral(is_com, data)
    if neutral is not None:
        is_rev = check_for_rev(is_com, neutral, data)
        if is_rev:
            if is_com:
                print("Abel group")
            else:
                print("group")
        else:
            if is_com:
                print("commutative monoid")
            else:
                print("monoid")
    else:
        print("semigroup")
else:
    print("magma")

commutative monoid
